export enum ParticipantRoles {
  OWNER = "OWNER",
  ADMIN = "ADMIN",
  MANAGER = "MANAGER",
  MODERATOR = "MODERATOR",
  PARTICIPANT = "PARTICIPANT",
}

export enum ParticipantStates {
  JOINED = "JOINED",
  EXITED = "EXITED",
  BANNED = "BANNED",
  KICKED = "KICKED",
}

export enum FriendsStates {
  NONE = "NONE",
  REQUESTED = "REQUESTED",
  FRIENDS = "FRIENDS",
}

export enum NotificationsTypes {
  CHAT_MESSAGE = "CHAT_MESSAGE",
  CALL_STARTED = "CALL_STARTED",
}

export enum PaymentState {
  PENDENT = 0,
  RECEIVED = 1,
  TEST = 2,
  UPGRADE = 3,
}

export enum PurchaseType {
  TEST = 0,
  PROMOTION = 1,
  NONE = 999
}

export enum CancelReasonType {
  SYSTEM = 0,
  USER = 1,
  REPLACE = 2,
  DEVELOPER = 3
}

export enum SubscriptionPeriod {
  MONTHLY = 0,
  QUARTERLY = 1,
  YEARLY = 2
}

export enum ReportType {
  SPAM = "SPAM",
  VIOLENCE = "VIOLENCE",
  SEXUAL = "SEXUAL",
  BULLYING = "BULLYING",
  RACISM = "RACISM",
  SCAM = "SCAM",
  FAKE = "FAKE_ACCOUNT",
  DMCA = "DMCA",
  OTHER = "OTHER",
}

export enum ReportToType {
  GROUP = "GROUP",
  USER = "USER",
  MESSAGE = "MESSAGE"
}

export enum ReportStatus {
  OPEN = "OPEN",
  FINISHED = "FINISHED"
}

export enum PenaltyType {
  WARNING = "WARNING", 
  RESTRICTION = "RESTRICTION", 
  TEMP_BAN = "TEMP_BAN", 
  PERM_BAN = "BANNED"
}

export enum FeedbackType {
  BUG = "BUG",
  SUGGESTION = "SUGGESTION",
  OTHER = "OTHER"
}

export enum GroupCategory {
  TECHNOLOGY = "TECHNOLOGY",
  EDUCATION = "EDUCATION",
  ENTERTAINMENT = "ENTERTAINMENT",
  SPORTS = "SPORTS",
  BUSINESS = "BUSINESS",
  HEALTH_AND_WELLNESS = "HEALTH_AND_WELLNESS",
  ART_AND_CULTURE = "ART_AND_CULTURE",
  TRAVEL = "TRAVEL",
  FOOD_AND_DRINK = "FOOD_AND_DRINK",
  GAMING = "GAMING",
  MUSIC = "MUSIC",
  SCIENCE = "SCIENCE",
  FASHION_AND_BEAUTY = "FASHION_AND_BEAUTY",
  FINANCE = "FINANCE",
  MARKETING = "MARKETING",
  PHOTOGRAPHY = "PHOTOGRAPHY",
  PETS_AND_ANIMALS = "PETS_AND_ANIMALS",
  REAL_ESTATE = "REAL_ESTATE",
  AUTOMOTIVE = "AUTOMOTIVE",
  DIY_AND_CRAFTS = "DIY_AND_CRAFTS",
  BOOKS_AND_LITERATURE = "BOOKS_AND_LITERATURE",
  PARENTING_AND_FAMILY = "PARENTING_AND_FAMILY",
  POLITICS_AND_SOCIETY = "POLITICS_AND_SOCIETY",
  RELIGION_AND_SPIRITUALITY = "RELIGION_AND_SPIRITUALITY",
  CAREER_AND_NETWORKING = "CAREER_AND_NETWORKING",
  FILM_AND_TV = "FILM_AND_TV",
  FITNESS_AND_BODYBUILDING = "FITNESS_AND_BODYBUILDING",
  OTHER = "OTHER",
}